### ISSUE TITLE
"light high contrast" color

### ISSUE THREAD

**Issue by arbor95** [ekdahl/webtrees-primer-theme#15]
change
![is](https://github.com/user-attachments/assets/9f2c7a5e-4229-4971-8e20-e3be03345723)
to
![may-be](https://github.com/user-attachments/assets/766fb49f-5aa5-4c4b-b42e-10b10b575dfd)

**Comment by ekdahl** [comment]
Header color is set to --bgColor-inset for all palettes, just like on GitHub.
![image](https://github.com/user-attachments/assets/9751a293-cbce-42cb-92ca-00e8f9b2548d)

**Comment by arbor95** [comment]
ok, your implementation is like githubs. For me, the github appearance is buggy (they forgot to change).
